-- Создаем независимую таблицу групп
CREATE TABLE student_group (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name VARCHAR(255) NOT NULL UNIQUE
);

-- Создаем независимую таблицу дисциплин
CREATE TABLE subjects (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL UNIQUE
);

-- Создаем независимую таблицу преподавателей
CREATE TABLE teachers (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          last_name VARCHAR(255) NOT NULL,
                          first_name VARCHAR(255) NOT NULL,
                          midle_name VARCHAR(255) NOT NULL
);

-- Создаем таблицу студентов (ссылается на student_group)
CREATE TABLE students (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          last_name VARCHAR(255) NOT NULL,
                          first_name VARCHAR(255) NOT NULL,
                          middle_name VARCHAR(255),
                          status VARCHAR(255) NOT NULL,
                          group_id BIGINT,
                          CONSTRAINT fk_students_group FOREIGN KEY (group_id) REFERENCES student_group (id)
);

-- Создаем таблицу занятий (ссылается на teachers, subjects, student_group)
CREATE TABLE lessons (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         date DATE NOT NULL,
                         lesson_number INT,
                         teacher_id BIGINT,
                         subject_id BIGINT,
                         group_id BIGINT,
                         CONSTRAINT fk_lessons_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (id),
                         CONSTRAINT fk_lessons_subject FOREIGN KEY (subject_id) REFERENCES subjects (id),
                         CONSTRAINT fk_lessons_group FOREIGN KEY (group_id) REFERENCES student_group (id)
);

-- Создаем таблицу посещаемости (ссылается на lessons, связь 1 к 1)
CREATE TABLE attendance (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            lesson_id BIGINT UNIQUE,
                            CONSTRAINT fk_attendance_lesson FOREIGN KEY (lesson_id) REFERENCES lessons (id)
);

-- Создаем связующую таблицу для связи "Многие ко Многим" (attendance и students)
CREATE TABLE attendance_students (
                                     attendance_id BIGINT NOT NULL,
                                     student_id BIGINT NOT NULL,
                                     PRIMARY KEY (attendance_id, student_id),
                                     CONSTRAINT fk_as_attendance FOREIGN KEY (attendance_id) REFERENCES attendance (id),
                                     CONSTRAINT fk_as_student FOREIGN KEY (student_id) REFERENCES students (id)
);